apiVersion: v1
kind: Service
metadata:
  name: k8s-yaml-generator-service
spec:
  selector:
    app: k8s-yaml-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Or ClusterIP, depending on your setup
